services:
  - type: web
    name: news-scraper
    env: python
    startCommand: python scraper_alerts.py
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: URL
        sync: false
      - key: KEYWORDS
        sync: false
      - key: CHECK_INTERVAL_SECONDS
        sync: false
